### ISSUE TITLE
Is it possible to use the preload function on local images?

### ISSUE THREAD

**Issue by joshglazer** [zyra/ionic-image-loader#130]
I would like to preload all of my images when my app loads for the first time.  I have tried adding the following code:

`imageLoader.preload("images/<filename>.png");`

It does not appear to be working, and I'm seeing the following error in xcode:

```
2018-01-24 20:05:15.708229-0500 Magic Words[10580:3485659] FileTransferError {
    body = "";
    code = 3;
    "http_status" = 0;
    source = "images/<filename>.png";
    target = "file:///var/mobile/Containers/Data/Application/FC5B2AD8-2BA3-4B26-81C7-B67903DB5AD9/Library/Caches/image-loader-cache/1931240270";
}
```

I am trying to do this in iOS.

**Comment by ihadeed** [comment]
I haven't tried that, and I don't think it's possible since this module uses an HTTP client to fetch the images.

I also don't see the point of doing that, if the image is stored in the filesystem, retrieving it on the spot would be as fast as retrieving it through this module. The `preload` function downloads images and stores them in the filesystem, not in the memory.

**Comment by joshglazer** [comment]
Even with the images on the filesystem, if I change the src of an image from one to another, there's a slight blip where no image shows.  I had an older ionic v1 app and used the ImageCacheFactory to fix a similar problem, and am looking to do the same thing for this app, which is using v3 of ionic.  I was hoping this plugin would do something similar, but if that isn't the case, do you know of any plugins that I could use?

Here is an example of the ionic v1 code that I used on my older project:

```
$ImageCacheFactory.Cache([
    "images/<filename>.gif"
]);
```

**Comment by ihadeed** [comment]
Try this https://github.com/Nodonisko/ionic-cache
