### ISSUE TITLE
Cannot find module "ionic-image-loader"

### ISSUE THREAD

**Issue by 0815nico** [zyra/ionic-image-loader#193]
Hello,

i installed everything how described in the readme, but i got this error if i try to launch the app. 

`[app-scripts]             Cannot find module 'ionic-image-loader'.
[app-scripts]        L3:  import { IonicApp, IonicModule, IonicErrorHandler } from 'ionic-angular';
[app-scripts]        L4:  import { IonicImageLoader } from 'ionic-image-loader';
[app-scripts]        L5:  import { MyApp } from './app.component';`

The package is in my package.json  

> "ionic-image-loader":  "^6.3.0",

And i got the folder in my node_modules

**Comment by mateusduraes** [comment]
Same here

**Comment by toshmark** [comment]
use 5.1.1 it works

**Comment by Stiveknx** [comment]
In npm, when the package was published, instead of placing index.js inside /dist/ another folder was created inside it (src/).
In package.json the main script is point to:
"main": "dist/index.js",

But since index.js is inside dist/src/ it doesn't find it.
I've cloned and changed the package.json file, poiting main to:
"main": "dist/src/index.js",
And worked.

Waiting for some fix from @ihadeed

**Comment by 0815nico** [comment]
Thats it. I changed it and now it is working.
Thank you @Stiveknx
