### ISSUE TITLE
ERROR: Download error code: 3 Live reload ionic 2

### ISSUE THREAD

**Issue by michaeljcoyne** [zyra/ionic-image-loader#35]
ERROR: Download error code: 3 Live reload ionic 2

I cant get this to work with live reload.

**Comment by ihadeed** [comment]
@michaeljcoyne this doesn't work with livereload since you cannot access the `file:///` protocol while in livereload. Images get loaded via regular HTTP loading when you're in livereload.

You shouldn't be having any issues, but I will look into this. Could you please provide me with steps to reproduce this?

I will modify the module soon so that it returns Base64 images in livereload (like what happens in WKWebView).

**Comment by michaeljcoyne** [comment]
Ok well a fallback would be good. Or a demonstration how to use it if there is one for dynamic images. Also I cant get the preload to work when I loop through images in my app component.

**Comment by ihadeed** [comment]
The latest version `3.1.0` will let you develop on livereload. Just set the return type to `base64` using the new `setReturnType` configuration method.
