### ISSUE TITLE
Platform ready event

### ISSUE THREAD

**Issue by tgensol** [zyra/ionic-image-loader#54]
Hi there,

When you do not have network, the plt.ready() promise can never be resolved.
Instead, the deviceready of cordova will always be resolved and faster. 

If you do not have network, the code will still work very well to cache and get your images cached. But if you still trust plt.ready, the cache can just not working at all..

If you changed the line 80 of image-loader.ts, you will see the cache will be way faster even when you have a good connection

Maybe there is a reason to use plt.ready(), but on my side, I do not have any issue by using  document.addEventListener('deviceready', function () {},false)

What do you think ? I can made a PR if needed

Best

**Comment by ihadeed** [comment]
This is interesting. I will have to do some testing, and dig through Ionic's code to figure out what is causing this. 

If you want to submit a PR to use an event listener for device ready event, that's fine. It shouldn't be an issue since that's all what we need.

Perhaps we should use an Observable to do this and use the .first() operator so the event listener will be cleared immediately. 

Code should look something like this:
Observable.fromEvent(document, 'deviceready').first().subscribe(...)

**Comment by tgensol** [comment]
Observable is a good idea. I will try your code tomorrow ! 

I created an issue on Ionic too, because I do not understand why the plt.ready Promise is taking so long and always depends on the network speed (But the app works fine with the deviceready event, and based on my tests, I do not have to wait the event of ionic ready for using the app)

Regards,

**Comment by ihadeed** [comment]
As far as I know platform.ready isn't dependent on network state. Cordova apps are built to work completely offline. But I do understand that platform.ready isn't simply just a wrapper for deviceready event. I remember the last time I looked at it, it had more logic.

**Comment by tgensol** [comment]
I think I found why. If you have external script (facebook pixel, google maps,....), even with the async command, ionic will wait for them to load....
