### ISSUE TITLE
Need information

### ISSUE THREAD

**Issue by duythien** [zyra/ionic-image-loader#67]
Hello

I have use this plugin then it work fine which some image, but when my app force loading image it seem that load all image is slow you can take my app at video https://www.youtube.com/watch?v=eGdIrBKM_kE

What is difference your plugin which that https://github.com/chrisben/imgcache.js/

**Comment by ihadeed** [comment]
Just had a quick at the library you linked to... this is what I see:
- you need to manually call a JavaScript API to cache the image, and to get it's cached URL
- it uses XHR requests to load images

Not sure if my observations or true or not, but here is what this module does:
- uses native background thread(s) to download images and then store them
- automatically cache and use the images, no need to do any manual API calls or DOM manipulations 
- built-in support for fallbacks images, customizing spinner .. etc

Since I haven't tried the `imgcache.js` library, I can't tell you all the differences, and I can't tell you which library would work better for you.

**Comment by duythien** [comment]
Ok thanks
