### ISSUE TITLE
<img-loader> tag broken for ionic 3 lazy loaded pages

### ISSUE THREAD

**Issue by sifang** [zyra/ionic-image-loader#93]
<img-loader> tag broken for ionic 3 lazy loaded page.
It works just for none-lazy loaded pages (declared and bootstrapped in AppModule)

Following is the error message:

ERROR Error: Uncaught (in promise): Error: Template parse errors:
Can't bind to 'src' since it isn't a known property of 'img-loader'.
1. If 'img-loader' is an Angular component and it has 'src' input, then verify that it is part of this module.
2. If 'img-loader' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
          >
            <img-loader  
              [ERROR ->][src] = "feed.d_pics[imgIndex]"
              [hidden]="!feed.d_picsLoaded || !feed.d_picsLoaded[0]" "): ng:///FeedDetailPageModule/FeedDetailPage.html@50:14

**Comment by sifang** [comment]
Looks like it IonicImageLoader needs to be imported in the lazy-loaded page.
In the module file, in my case is "feed-detail/feed-detail.module.ts", add the import like so:

```
import { NgModule } from '@angular/core';
import { IonicPageModule } from 'ionic-angular';
import { FeedDetailPage } from './feed-detail';
import { IonicImageLoader } from 'ionic-image-loader';

@NgModule({
  declarations: [
    FeedDetailPage,
  ],
  imports: [
    IonicPageModule.forChild(FeedDetailPage),
    IonicImageLoader
  ],
})
export class FeedDetailPageModule {}
```

**Comment by ihadeed** [comment]
Hey there,

Whenever you lazy load a component/page, that module is independent and does not share the imported modules from root modules. It can only access providers that are imported. Which is why in your app's root module you need to import `IonicImageLoader.forRoot()` and in the child modules you import `IonicImageLoader`.

I've updated the example project to demonstrate lazy loading usage.

**Comment by robertnicjoo** [comment]
Sorry to bring this up after very long time, but i'm using **@ beta version [1]**  in **ionic 4** and getting very same error, I followed everything by documents yet it return error.


app module:

```php
import { IonicImageLoader } from 'ionic-image-loader';


@NgModule({
//....
  imports: [
    IonicImageLoader.forRoot()
  ],
//....
})
export class AppModule {}
```

Also in my page module i have

```php
import { ImageLoaderConfigService  } from 'ionic-image-loader';

export class HomePage  implements OnInit {
   constructor(private categoriesService: CategoriesService, private imageLoaderConfig: ImageLoaderConfigService) {}
//.....
}
```

### Note [1]:

Beta version isn't supported in documents I had a hard time to find right elements to use it in my module this `import { ImageLoaderConfigService  } from 'ionic-image-loader';` isn't supported anywhere and when I tried to use other elements like

```php
IonicImageLoader

ImageLoaderConfig

ImgLoaderComponent
```
 instead of
```php
ImageLoaderConfigService
```
kept returning errors as those elements didn't know anything about 

```php
enableDebugMode
enableFallbackAsPlaceholder
setFallbackUrl
setMaximumCacheAge
cache
//etc.
```
PLEASE add **@ beta version** into readme as well.

Thank you.
