### ISSUE TITLE
image is showing link broken 

### ISSUE THREAD

**Issue by 9meAhmed** [zyra/ionic-image-loader#94]
![capture1](https://user-images.githubusercontent.com/17180707/29759945-62c61c80-8bd9-11e7-8ca9-4fc94ad0df68.PNG)
![capture](https://user-images.githubusercontent.com/17180707/29760049-2bb901fc-8bda-11e7-9a58-a2f0d93765f9.PNG)

i have commented the html for now
![Uploading Capture.PNG…]()
![capture1](https://user-images.githubusercontent.com/17180707/29760050-2bbee04a-8bda-11e7-9a5f-58b2c37755c4.PNG)

**Comment by frangovalex** [comment]
Same problem

**Comment by itsru** [comment]
same problem 

What version of the package and plugins are you running? 
Check your package.json - I had to revert to the following
```
"@ionic-native/core": "4.2.1",
"@ionic-native/file": "4.2.1",
"@ionic-native/file-transfer": "4.2.1",
"cordova-plugin-file": "^4.3.3",
"cordova-plugin-file-transfer": "^1.6.3",
"ionic-image-loader": "4.2.1"
```

additionally are your images stored as base64? If ao are you setting `setImageReturnType('base64');`

**Comment by fbrun** [comment]
I have same problem but with external url scheme without 'http' mentionned.
The src link is like '//url_to_img', so img-loader try to find it at 'file://url_to_img' instead of 'http://url_to_img'

My package.json:
<pre>
"@ionic-native/core": "4.2.1",
"@ionic-native/device": "4.2.1",
"@ionic-native/fcm": "4.2.1",
"@ionic-native/file": "4.2.1",
"@ionic-native/file-opener": "4.2.1",
"@ionic-native/file-transfer": "4.2.1",
"ionic-angular": "3.6.1",
"ionic-image-loader": "4.2.1"
</pre>

**Comment by mtshare** [comment]
Same for me! Any solutions?

**Comment by maximcamario** [comment]
Same issue. Is there any solution?
